services:

  xyb-test:
    container_name: xyb-test
    image: ccr.ccs.tencentyun.com/xiaoyibao/dow-gewe-official-simplified-xyb:v5 #本地构建的新定制image
    # image: hanfangyuan/dify-on-wechat:latest
    restart: unless-stopped
    ports:
      - "9919:9919"
    security_opt:
      - seccomp:unconfined
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - ./tmp:/app/tmp #存储图片的目录
      - ./plugins/hello:/app/plugins/hello #定制欢迎词的插件目录
      - ./run.log:/app/run.log #日志
      - ./config.json:/app/config.json #配置文件
      - ./config.py:/app/config.py #配置文件
